[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools_scm[toml]"
]
build-backend = "setuptools.build_meta"

[project]
name = "mc_bin_client"
version = "1.0.1"
description = "Binary memcached client"

[tool.setuptools]
packages = [
    "mc_bin_client",
]
include-package-data = true